config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  get 'items/index'
  get 'items_imports/new'
  get 'items_imports/create'
  resources :items
  resources :items_imports
  root to: "students#index"
  resources :students
  devise_for :users, skip: :omniauth_callbacks
  get '/search' => 'search#search_student'
  get '/search1' => 'search#search_book'
  resources :messages
  get 'pages/home'
  get 'download_sample_excel' => 'items_imports#download_sample_excel'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("header.rails_final_project_2_application") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if current_user %>
  <%= link_to t('header.new_student'), new_student_path, class: "btn btn-primary" %>
  <%= link_to t("header.student_list"), root_path, class: "btn btn-primary" %>
  <%= link_to t("header.items_list"), items_path, class: "btn btn-primary" %>
  <%= link_to t("header.live_messages"), messages_path, class: "btn btn-primary" %>
  <%= link_to t("header.home"), root_path, class: "btn btn-primary" %>
  <%= link_to t("header.sign_out"), destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
  <% else %>
    <%= link_to t("header.sign_in"), new_user_session_path, class: "btn btn-primary" %>
    <%= link_to t("header.sign_up"), new_user_registration_path, class: "btn btn-primary" %>
  <% end %>
  <%= link_to t('header.russian'), root_path(locale: :ru), class: "btn btn-primary" %>
  <%= link_to t('header.english'), root_path(locale: :en), class: "btn btn-primary" %>
  <%= link_to t('header.hindi'), root_path(locale: :hi), class: "btn btn-primary" %>
  <%= link_to t('header.marathi'), root_path(locale: :mr), class: "btn btn-primary" %>
  <%= link_to t('header.japanese'), root_path(locale: :ja), class: "btn btn-primary" %>
  <%= link_to t('header.urdu'), root_path(locale: :ur), class: "btn btn-primary" %>
  <%= yield %>
  </body>
</html>